services:
  - type: web
    name: otp-spam-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_SECRET
        generateValue: true
      - key: MAX_THREADS
        value: "5000000000"
      - key: MAX_SPAM_PER_PHONE
        value: "1000000000"
      - key: SPAM_COOLDOWN_HOURS
        value: "24"
